version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: poseidon_lms
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    command: ["sh", "./scripts/docker-entrypoint.sh"]
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-dev-secret-change-me}
      NEXTAUTH_URL: http://localhost:3000
      # Optional if your app uses a DB later; NextAuth with credentials + JWT does not require it
      DATABASE_URL: ${DATABASE_URL:-}
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - db

volumes:
  postgres-data: